[package]
name = "builder_card"
version = "0.1.0"
edition = "2024"

[dependencies]
builder_registry = { git = "https://github.com/Cryptita-Plays/cryptita-builder-registry.git", subdir = "builder_registry", rev = "main" }